# Generated by Django 4.1.6 on 2023-02-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidad', models.DecimalField(decimal_places=2, max_digits=6)),
                ('marca', models.CharField(max_length=10)),
                ('modelo', models.CharField(max_length=4)),
                ('placa', models.CharField(max_length=8)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Viajando', 'Viaje'), ('Reparaciones', 'Reparaciones')], default='Disponible', max_length=12)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combustible', models.DecimalField(decimal_places=2, max_digits=5)),
                ('viaticos', models.DecimalField(decimal_places=2, max_digits=5)),
                ('peajes', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.DateTimeField(auto_now_add=True)),
                ('destino', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
