# Generated by Django 4.1.6 on 2023-02-17 12:41

import camion.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camion',
            name='created',
        ),
        migrations.RemoveField(
            model_name='camion',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='camion',
            name='updated',
        ),
        migrations.AlterField(
            model_name='camion',
            name='placa',
            field=models.CharField(max_length=8, validators=[camion.validators.validar_cuatro_cifras]),
        ),
    ]
