# Generated by Django 4.1.6 on 2023-02-17 12:44

import camion.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camion', '0002_remove_camion_created_remove_camion_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camion',
            name='modelo',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='camion',
            name='placa',
            field=models.DecimalField(decimal_places=0, max_digits=5, validators=[camion.validators.validar_cuatro_cifras]),
        ),
    ]
