# Generated by Django 4.1.6 on 2023-02-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camion', '0005_alter_camion_placa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camion',
            name='modelo',
            field=models.CharField(max_length=4),
        ),
    ]
